"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { AddToCalendar } from "@/components/invitation/AddToCalendar";
import { Countdown } from "@/components/invitation/Countdown";
import { EventMusic } from "@/components/invitation/EventMusic";
import { ScrollReveal } from "@/components/motion/ScrollReveal";
import type { InvitationEvent } from "@/types/invitation";

export function XVGlamInvitation({ event }: { event: InvitationEvent }) {
  return <main className="glam-02"><GlamOpening event={event} /><EventMusic music={event.music} className="glam-music" /><GlamHero event={event} /><ScrollReveal className="glam-reveal"><GlamDate event={event} /></ScrollReveal><ScrollReveal className="glam-reveal"><GlamLocations event={event} /></ScrollReveal><ScrollReveal className="glam-reveal"><GlamAgenda event={event} /></ScrollReveal><ScrollReveal className="glam-reveal"><GlamGallery photos={event.gallery ?? []} /></ScrollReveal><ScrollReveal className="glam-reveal"><GlamDress dress={event.dressCode} /></ScrollReveal>{event.giftRegistry && <ScrollReveal className="glam-reveal"><section className="glam-gifts"><p>DETALLES</p><h2>{event.giftRegistry.title ?? "Mesa de regalos"}</h2><span>{event.giftRegistry.description}</span>{event.giftRegistry.url && <a href={event.giftRegistry.url} target="_blank" rel="noreferrer">{event.giftRegistry.buttonLabel ?? "Ver opciones"}</a>}</section></ScrollReveal>}<ScrollReveal className="glam-reveal"><GlamRSVP event={event} /></ScrollReveal><GlamClosing event={event} /></main>;
}

function GlamOpening({ event }: { event: InvitationEvent }) { const [visible, setVisible] = useState(false); const [opening, setOpening] = useState(false); const key = `glam-opening:${event.eventLabel}-${event.honoreeName}-${event.date}`; useEffect(() => { if (event.openingExperience?.enabled && event.openingExperience.type === "cinematic-reveal" && !sessionStorage.getItem(key)) setVisible(true); }, [event.openingExperience, key]); useEffect(() => { if (!visible) return; const old = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = old; }; }, [visible]); if (!visible) return null; const open = () => { if (event.openingExperience?.playMusicOnOpen && event.music?.src && event.music.enabled !== false) window.dispatchEvent(new Event("invitation:play-music")); sessionStorage.setItem(key, "done"); if (matchMedia("(prefers-reduced-motion: reduce)").matches) { setVisible(false); return; } setOpening(true); window.setTimeout(() => setVisible(false), 1300); }; return <section className={`glam-opening ${opening ? "is-opening" : ""}`} style={{ backgroundImage: `url(${event.heroImage})` }}><button onClick={open} aria-label={event.openingExperience?.prompt ?? "Toca para descubrir"}><b>XV</b><time>{event.displayDate}</time><span>{event.openingExperience?.prompt ?? "Toca para descubrir"}</span></button></section>; }
function GlamHero({ event }: { event: InvitationEvent }) { return <section className="glam-hero" style={{ backgroundImage: `linear-gradient(0deg,rgba(8,13,28,.94),rgba(8,13,28,.18)),url(${event.heroImage})` }}><p>MIS XV</p><h1>{event.honoreeName}</h1><span>{event.introText}</span></section>; }
function GlamDate({ event }: { event: InvitationEvent }) { const date = new Date(event.date); return <section className="glam-date"><div><strong>{String(date.getDate()).padStart(2, "0")}</strong><p>{date.toLocaleDateString("es-MX", { month: "long" }).toUpperCase()}<br />{date.getFullYear()}</p></div><Countdown date={event.date} />{event.calendar && <AddToCalendar calendar={event.calendar} compact />}</section>; }
function GlamLocations({ event }: { event: InvitationEvent }) { return <section className="glam-locations">{[event.ceremony, event.reception].filter(Boolean).map(location => location && <article key={location.label}>{location.image ? <Image src={location.image} alt={location.imageAlt ?? location.venue} fill sizes="(max-width:700px) 100vw, 50vw" /> : <div className="glam-location-fallback">✦</div>}<div><p>{location.label}</p><time>{location.time}</time><h2>{location.venue}</h2><span>{location.address}</span><a href={location.mapUrl} target="_blank" rel="noreferrer">Ver ubicación</a></div></article>)}</section>; }
function GlamAgenda({ event }: { event: InvitationEvent }) { return <section className="glam-agenda"><p>LA NOCHE</p><h2>Agenda</h2>{event.itinerary?.map((item, index) => <div key={`${item.time}-${item.title}`} className={index === 1 || index === 3 ? "featured" : ""}><time>{item.time}</time><strong>{item.title}</strong></div>)}</section>; }
function GlamGallery({ photos }: { photos: InvitationEvent["gallery"] extends infer T ? NonNullable<T> : never }) { const [active, setActive] = useState<number | null>(null); const [mounted, setMounted] = useState(false); useEffect(() => setMounted(true), []); if (!photos.length) return null; const move = (n: number) => setActive((n + photos.length) % photos.length); return <section className="glam-gallery"><p>RECUERDOS</p><h2>Momentos para siempre</h2><div className="glam-slider"><button aria-label="Foto anterior" onClick={() => move((active ?? 0) - 1)}>‹</button><button className="glam-main-photo" onClick={() => setActive(active ?? 0)}><Image src={photos[active ?? 0].src} alt={photos[active ?? 0].alt} fill sizes="80vw" /></button><button aria-label="Foto siguiente" onClick={() => move((active ?? 0) + 1)}>›</button></div><div className="glam-dots">{photos.map((_, i) => <button key={i} aria-label={`Ver foto ${i + 1}`} className={i === (active ?? 0) ? "active" : ""} onClick={() => setActive(i)} />)}</div>{mounted && active !== null ? createPortal(<div className="gallery-lightbox" role="dialog" aria-modal="true" onClick={() => setActive(null)}><div className="gallery-lightbox-content" onClick={e => e.stopPropagation()}><Image className="lightbox-image" src={photos[active].src} alt={photos[active].alt} fill sizes="100vw" /></div><button className="lightbox-close" aria-label="Cerrar galería" onClick={e => { e.stopPropagation(); setActive(null); }}>×</button></div>, document.body) : null}</section>; }
function GlamDress({ dress }: { dress?: InvitationEvent["dressCode"] }) { if (!dress) return null; return <section className="glam-dress"><p>FASHION NOTE</p><div className="glam-fashion-icons"><i>♢</i><i>♧</i></div><h2>{dress.style}</h2>{dress.groups?.map(group => <p key={group.label}><b>{group.label}</b> {group.description}</p>)}{dress.reservedColors?.length ? <div>Color reservado {dress.reservedColors.map(color => typeof color === "string" ? <span key={color} style={{ background: color }} /> : <span key={color.value} style={{ background: color.value }} title={color.label} />)}</div> : null}</section>; }
function GlamRSVP({ event }: { event: InvitationEvent }) { const href = `https://wa.me/${event.rsvp.phone.replace(/\D/g, "")}?text=${encodeURIComponent(event.rsvp.message)}`; return <section className="glam-rsvp" style={{ backgroundImage: `linear-gradient(0deg,rgba(5,10,23,.94),rgba(5,10,23,.45)),url(${event.closingImage ?? event.heroImage})` }}><p>CONFIRMA</p><h2>TU ASISTENCIA</h2><span>Será un gusto compartir este día contigo.</span><a href={href} target="_blank" rel="noreferrer">Confirmar en WhatsApp</a></section>; }
function GlamClosing({ event }: { event: InvitationEvent }) { return <section className="glam-closing" style={{ backgroundImage: `linear-gradient(0deg,rgba(8,13,28,.83),rgba(8,13,28,.22)),url(${event.closingImage ?? event.heroImage})` }}><h2>Nos vemos en mis XV</h2><p>Gracias por ser parte de esta noche tan especial.</p></section>; }
